# Generated by Django 5.2.16 on 2026-08-12 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('indicators', models.JSONField(default=dict, help_text='RSI, MACD, EMA, VWAP, etc.')),
                ('pattern', models.CharField(blank=True, help_text='Detected candle pattern', max_length=50)),
                ('market_condition', models.CharField(blank=True, max_length=50)),
                ('price_change', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('volume_change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('source', models.CharField(default='binance', help_text='binance, coingecko, etc.', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'candle data',
                'verbose_name_plural': 'candle data',
                'db_table': 'candle_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_features', models.JSONField(default=dict, help_text='Features used to make the prediction')),
                ('actual_outcome', models.CharField(help_text='buy, sell, hold - what happened', max_length=20)),
                ('actual_return', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('candle_open', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('candle_high', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('candle_low', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('candle_close', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('candle_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('next_candles', models.JSONField(default=list, help_text='Next N candles after signal for pattern learning')),
                ('was_correct', models.BooleanField(default=False)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'training sample',
                'verbose_name_plural': 'training samples',
                'db_table': 'training_samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='marketmemory',
            new_name='market_memo_symbol_f7d77c_idx',
            old_name='market_memo_symbol_idx',
        ),
        migrations.RenameIndex(
            model_name='marketmemory',
            new_name='market_memo_market__68473d_idx',
            old_name='market_memo_condit_idx',
        ),
        migrations.AddIndex(
            model_name='candledata',
            index=models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='candle_data_symbol_f43417_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candledata',
            unique_together={('symbol', 'timeframe', 'timestamp')},
        ),
        migrations.AddField(
            model_name='trainingsample',
            name='candle_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.candledata'),
        ),
        migrations.AddField(
            model_name='trainingsample',
            name='signal_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to='feedback.signalmemory'),
        ),
    ]
