# Generated by Django 5.2.16 on 2026-08-11 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device token',
                'verbose_name_plural': 'device tokens',
                'db_table': 'mobile_device_tokens',
            },
        ),
        migrations.CreateModel(
            name='MobileAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('alert_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('change_pct', 'Change %'), ('volume_spike', 'Volume Spike'), ('signal_buy', 'Buy Signal'), ('signal_sell', 'Sell Signal')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_count', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mobile alert',
                'verbose_name_plural': 'mobile alerts',
                'db_table': 'mobile_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('price_ticker', 'Price Ticker'), ('portfolio_summary', 'Portfolio Summary'), ('signal_list', 'Signal List'), ('watchlist', 'Watchlist')], max_length=30)),
                ('config', models.JSONField(default=dict)),
                ('position', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mobile widget',
                'verbose_name_plural': 'mobile widgets',
                'db_table': 'mobile_widgets',
                'ordering': ['position'],
            },
        ),
    ]
