# Generated by Django 5.2.17 on 2026-08-11 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmartMoneyEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("accumulation", "Accumulation"),
                            ("distribution", "Distribution"),
                            ("breakout", "Breakout"),
                            ("fakeout", "Fakeout"),
                            ("stop_hunt", "Stop Hunt"),
                            ("liquidity_sweep", "Liquidity Sweep"),
                            ("order_block", "Order Block"),
                            ("fair_value_gap", "Fair Value Gap"),
                            ("breaker_block", "Breaker Block"),
                            ("mitigation_block", "Mitigation Block"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(choices=[("bullish", "Bullish"), ("bearish", "Bearish")], max_length=20),
                ),
                ("confidence", models.FloatField(default=0.5, help_text="Event confidence 0-1")),
                ("price_level", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume_confirmation", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("timeframe", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Smart money event",
                "verbose_name_plural": "Smart money events",
                "db_table": "technical_analysis_smart_money_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalPattern",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(db_index=True, max_length=10)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("head_shoulders", "Head and Shoulders"),
                            ("head_shoulders_inv", "Inverse Head and Shoulders"),
                            ("double_top", "Double Top"),
                            ("double_bottom", "Double Bottom"),
                            ("triple_top", "Triple Top"),
                            ("triple_bottom", "Triple Bottom"),
                            ("ascending_triangle", "Ascending Triangle"),
                            ("descending_triangle", "Descending Triangle"),
                            ("symmetrical_triangle", "Symmetrical Triangle"),
                            ("bull_flag", "Bull Flag"),
                            ("bear_flag", "Bear Flag"),
                            ("wedge_falling", "Falling Wedge"),
                            ("wedge_rising", "Rising Wedge"),
                            ("channel_up", "Ascending Channel"),
                            ("channel_down", "Descending Channel"),
                            ("cup_handle", "Cup and Handle"),
                            ("rounding_bottom", "Rounding Bottom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("bearish", "Bearish"), ("neutral", "Neutral")], max_length=20
                    ),
                ),
                ("confidence", models.FloatField(default=0.5, help_text="Pattern confidence 0-1")),
                ("start_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("end_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("target_price", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("stop_price", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Technical pattern",
                "verbose_name_plural": "Technical patterns",
                "db_table": "technical_analysis_patterns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportResistance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(db_index=True, max_length=10)),
                (
                    "level_type",
                    models.CharField(
                        choices=[("support", "Support"), ("resistance", "Resistance"), ("pivot", "Pivot Point")],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("strength", models.IntegerField(default=50, help_text="Level strength 0-100")),
                ("touch_count", models.IntegerField(default=1, help_text="Number of times tested")),
                ("last_test_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Support/Resistance level",
                "verbose_name_plural": "Support/Resistance levels",
                "db_table": "support_resistance",
                "ordering": ["symbol", "price"],
                "unique_together": {("symbol", "timeframe", "level_type", "price")},
            },
        ),
        migrations.CreateModel(
            name="TechnicalAnalysisResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(db_index=True, max_length=10)),
                (
                    "overall_signal",
                    models.CharField(
                        choices=[
                            ("strong_buy", "Strong Buy"),
                            ("buy", "Buy"),
                            ("neutral", "Neutral"),
                            ("sell", "Sell"),
                            ("strong_sell", "Strong Sell"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.5, help_text="Overall confidence 0-1")),
                ("indicators_summary", models.JSONField(default=dict, help_text="Summary of all indicators")),
                ("patterns_summary", models.JSONField(default=list, help_text="Detected patterns")),
                ("support_levels", models.JSONField(default=list, help_text="Key support levels")),
                ("resistance_levels", models.JSONField(default=list, help_text="Key resistance levels")),
                ("trend_summary", models.JSONField(default=dict, help_text="Trend analysis summary")),
                ("smart_money_summary", models.JSONField(default=list, help_text="Smart money events")),
                ("entry_price", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("stop_loss", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("take_profit_1", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("take_profit_2", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("take_profit_3", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("risk_reward_ratio", models.FloatField(default=0, help_text="Risk/Reward ratio")),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Technical analysis result",
                "verbose_name_plural": "Technical analysis results",
                "db_table": "technical_analysis_results",
                "ordering": ["-timestamp"],
                "unique_together": {("symbol", "timeframe", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="TechnicalIndicator",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(db_index=True, max_length=10)),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("rsi", "RSI"),
                            ("macd", "MACD"),
                            ("bollinger_bands", "Bollinger Bands"),
                            ("ema", "EMA"),
                            ("sma", "SMA"),
                            ("stochastic", "Stochastic"),
                            ("atr", "ATR"),
                            ("adx", "ADX"),
                            ("obv", "OBV"),
                            ("vwap", "VWAP"),
                            ("ichimoku", "Ichimoku Cloud"),
                            ("cci", "CCI"),
                            ("williams_r", "Williams %R"),
                            ("mfi", "Money Flow Index"),
                            ("roc", "Rate of Change"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.JSONField(default=dict, help_text="Indicator value(s)")),
                (
                    "signal",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("bearish", "Bearish"), ("neutral", "Neutral")],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("strength", models.IntegerField(default=50, help_text="Signal strength 0-100")),
                ("period", models.IntegerField(default=14, help_text="Indicator period")),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Technical indicator",
                "verbose_name_plural": "Technical indicators",
                "db_table": "technical_indicators",
                "ordering": ["-timestamp"],
                "unique_together": {("symbol", "timeframe", "indicator_type", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(db_index=True, max_length=10)),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("strong_uptrend", "Strong Uptrend"),
                            ("uptrend", "Uptrend"),
                            ("sideways", "Sideways"),
                            ("downtrend", "Downtrend"),
                            ("strong_downtrend", "Strong Downtrend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trend_strength", models.IntegerField(default=50, help_text="Trend strength 0-100")),
                ("adx_value", models.FloatField(default=0, help_text="ADX value for trend strength")),
                ("trend_start_price", models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ("trend_start_time", models.DateTimeField(null=True)),
                ("current_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("ema_short", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("ema_long", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                (
                    "ema_signal",
                    models.CharField(
                        choices=[
                            ("bullish_cross", "Bullish Cross"),
                            ("bearish_cross", "Bearish Cross"),
                            ("bullish_alignment", "Bullish Alignment"),
                            ("bearish_alignment", "Bearish Alignment"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trend analysis",
                "verbose_name_plural": "Trend analyses",
                "db_table": "trend_analysis",
                "ordering": ["-timestamp"],
                "unique_together": {("symbol", "timeframe", "timestamp")},
            },
        ),
    ]
