"""Initial migration for signals app."""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(max_length=20, choices=[
                    ('buy', 'Buy'), ('strong_buy', 'Strong Buy'), ('sell', 'Sell'),
                    ('strong_sell', 'Strong Sell'), ('hold', 'Hold'), ('wait', 'Wait'),
                    ('exit', 'Exit'), ('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'),
                ])),
                ('confidence', models.IntegerField(default=50)),
                ('risk_score', models.IntegerField(default=50)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.JSONField(default=list)),
                ('timeframe', models.CharField(max_length=10)),
                ('technical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('news_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('macro_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('historical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('composite_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'signal',
                'verbose_name_plural': 'signals',
                'db_table': 'signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_type', models.CharField(max_length=20, choices=[
                    ('technical', 'Technical'), ('news', 'News'), ('macro', 'Macro'),
                    ('ai', 'AI'), ('sentiment', 'Sentiment'), ('risk', 'Risk'),
                ])),
                ('description', models.TextField()),
                ('confidence', models.IntegerField(default=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='signals.signal')),
            ],
            options={
                'verbose_name': 'signal reason',
                'verbose_name_plural': 'signal reasons',
                'db_table': 'signal_reasons',
            },
        ),
        migrations.CreateModel(
            name='SignalGenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('input_data', models.JSONField(default=dict)),
                ('weights_used', models.JSONField(default=dict)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'signal generation request',
                'verbose_name_plural': 'signal generation requests',
                'db_table': 'signal_generation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactorWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=4, default=0.2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'factor weight',
                'verbose_name_plural': 'factor weights',
                'db_table': 'factor_weights',
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_portfolio_risk', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('max_position_size', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('max_correlated_positions', models.IntegerField(default=3)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('risk_per_trade', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('use_kelly_criterion', models.BooleanField(default=False)),
                ('kelly_fraction', models.DecimalField(decimal_places=2, default=0.25, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'risk profile',
                'verbose_name_plural': 'risk profiles',
                'db_table': 'risk_profiles',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unrealized_pnl_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('risk_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.signal')),
            ],
            options={
                'verbose_name': 'portfolio position',
                'verbose_name_plural': 'portfolio positions',
                'db_table': 'portfolio_positions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_return', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('actual_return_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('max_favorable', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('max_adverse', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('holding_period_hours', models.IntegerField(default=0)),
                ('hit_stop_loss', models.BooleanField(default=False)),
                ('hit_take_profit', models.BooleanField(default=False)),
                ('was_correct', models.BooleanField(default=False)),
                ('score_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='signals.signal')),
            ],
            options={
                'verbose_name': 'signal performance',
                'verbose_name_plural': 'signal performances',
                'db_table': 'signal_performances',
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=20)),
                ('final_capital', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_return', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_return_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('avg_win', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_loss', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('trades_data', models.JSONField(default=list)),
                ('equity_curve', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'backtest result',
                'verbose_name_plural': 'backtest results',
                'db_table': 'backtest_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
