# Generated by Django 5.2.16 on 2026-08-12 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_seed_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('alert_type', models.CharField(choices=[('rsi_above', 'RSI Above'), ('rsi_below', 'RSI Below'), ('confidence_above', 'Confidence Above'), ('confidence_below', 'Confidence Below'), ('composite_above', 'Composite Score Above'), ('composite_below', 'Composite Score Below'), ('technical_above', 'Technical Score Above'), ('technical_below', 'Technical Score Below'), ('sentiment_above', 'Sentiment Score Above'), ('sentiment_below', 'Sentiment Score Below'), ('price_above', 'Price Above'), ('price_below', 'Price Below'), ('change_pct_above', '24h Change Above %'), ('change_pct_below', '24h Change Below %'), ('signal_buy', 'Buy Signal'), ('signal_sell', 'Sell Signal'), ('signal_strong_buy', 'Strong Buy Signal'), ('signal_strong_sell', 'Strong Sell Signal')], max_length=30)),
                ('threshold', models.FloatField(default=50, help_text='Threshold value to trigger alert')),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='Minutes between repeated alerts')),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('message_template', models.CharField(blank=True, help_text='Custom alert message', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alert rule',
                'verbose_name_plural': 'alert rules',
                'db_table': 'alert_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_value', models.FloatField(default=0, help_text='Actual value that triggered the alert')),
                ('message', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='signals.alertrule')),
            ],
            options={
                'verbose_name': 'alert history',
                'verbose_name_plural': 'alert histories',
                'db_table': 'alert_history',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
