# Generated by Django 5.2.16 on 2026-08-13 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alertrule_alerthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_name', models.CharField(db_index=True, max_length=50)),
                ('old_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('new_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('win_rate_before', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('win_rate_after', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('signals_evaluated', models.IntegerField(default=0)),
                ('adjustment_type', models.CharField(choices=[('performance', 'Performance-based'), ('manual', 'Manual adjustment'), ('scheduled', 'Scheduled optimization')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'weight history',
                'verbose_name_plural': 'weight history',
                'db_table': 'weight_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
