# Generated by Django 5.2.16 on 2026-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_weighthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='cagr',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='execution_mode',
            field=models.CharField(choices=[('paper', 'Paper Trading'), ('shadow', 'Shadow Trading'), ('backtest', 'Backtest')], default='backtest', max_length=20),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='expectancy',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='feature_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='fee_rate',
            field=models.DecimalField(decimal_places=6, default=0.001, help_text='Fee rate per trade (e.g. 0.001 = 0.1%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='max_adverse_excursion',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='max_favorable_excursion',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='signal_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of signal engine state at time of backtest'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='slippage_rate',
            field=models.DecimalField(decimal_places=6, default=0.0005, help_text='Slippage rate per trade (e.g. 0.0005 = 0.05%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='sortino_ratio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='strategy_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='total_fees',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='total_slippage',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='weight_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Factor weights used during backtest'),
        ),
    ]
