# Generated by Django 5.2.16 on 2026-08-14 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_backtest_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkForwardRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(max_length=100)),
                ('strategy_version', models.CharField(default='1.0', max_length=50)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('train_days', models.IntegerField(default=90, help_text='Training window in days')),
                ('validate_days', models.IntegerField(default=30, help_text='Validation window in days')),
                ('test_days', models.IntegerField(default=30, help_text='Test/OOS window in days')),
                ('step_days', models.IntegerField(default=30, help_text='Rolling step in days')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=20)),
                ('fee_rate', models.DecimalField(decimal_places=6, default=0.001, max_digits=10)),
                ('slippage_rate', models.DecimalField(decimal_places=6, default=0.0005, max_digits=10)),
                ('total_windows', models.IntegerField(default=0)),
                ('avg_oos_return', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_oos_sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_oos_win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oos_vs_is_ratio', models.DecimalField(decimal_places=4, default=0, help_text='OOS performance / IS performance ratio', max_digits=5)),
                ('max_oos_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('leakage_detected', models.BooleanField(default=False)),
                ('leakage_details', models.JSONField(blank=True, default=dict)),
                ('weight_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'walk-forward run',
                'verbose_name_plural': 'walk-forward runs',
                'db_table': 'walk_forward_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkForwardWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_index', models.IntegerField(default=0)),
                ('train_start', models.DateTimeField()),
                ('train_end', models.DateTimeField()),
                ('validate_start', models.DateTimeField()),
                ('validate_end', models.DateTimeField()),
                ('test_start', models.DateTimeField()),
                ('test_end', models.DateTimeField()),
                ('is_return_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_trades', models.IntegerField(default=0)),
                ('is_max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('oos_return_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('oos_sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('oos_win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oos_trades', models.IntegerField(default=0)),
                ('oos_max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('frozen_weights', models.JSONField(blank=True, default=dict)),
                ('is_equity_curve', models.JSONField(blank=True, default=list)),
                ('oos_equity_curve', models.JSONField(blank=True, default=list)),
                ('is_backtest_result', models.JSONField(blank=True, default=dict)),
                ('oos_backtest_result', models.JSONField(blank=True, default=dict)),
                ('has_leakage', models.BooleanField(default=False)),
                ('leakage_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='signals.walkforwardrun')),
            ],
            options={
                'verbose_name': 'walk-forward window',
                'verbose_name_plural': 'walk-forward windows',
                'db_table': 'walk_forward_windows',
                'ordering': ['run', 'window_index'],
            },
        ),
    ]
