# Generated by Django 5.2.16 on 2026-08-14 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_walk_forward_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillSwitchState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('triggered_by', models.CharField(blank=True, help_text='What triggered the kill switch', max_length=100)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('portfolio_drawdown_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('daily_pnl_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('active_positions', models.IntegerField(default=0)),
                ('total_exposure_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kill switch state',
                'verbose_name_plural': 'kill switch states',
                'db_table': 'kill_switch_state',
            },
        ),
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_risk_per_trade', models.DecimalField(decimal_places=2, default=1.0, help_text='Max risk per trade as % of account', max_digits=5)),
                ('max_position_size_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Max single position as % of account', max_digits=5)),
                ('max_concurrent_positions', models.IntegerField(default=5, help_text='Maximum open positions')),
                ('max_correlated_positions', models.IntegerField(default=3, help_text='Max positions in correlated assets')),
                ('max_portfolio_risk_pct', models.DecimalField(decimal_places=2, default=5.0, help_text='Max total portfolio risk as %', max_digits=5)),
                ('max_portfolio_exposure_pct', models.DecimalField(decimal_places=2, default=50.0, help_text='Max total exposure as %', max_digits=5)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=2, default=15.0, help_text='Max drawdown before kill switch', max_digits=5)),
                ('daily_loss_limit_pct', models.DecimalField(decimal_places=2, default=3.0, help_text='Max daily loss as %', max_digits=5)),
                ('kill_switch_enabled', models.BooleanField(default=True)),
                ('kill_on_drawdown', models.BooleanField(default=True, help_text='Trigger on max drawdown')),
                ('kill_on_daily_loss', models.BooleanField(default=True, help_text='Trigger on daily loss limit')),
                ('kill_on_data_feed_failure', models.BooleanField(default=True, help_text='Trigger if data feeds fail')),
                ('kill_on_api_failure', models.BooleanField(default=True, help_text='Trigger if exchange API fails')),
                ('kill_on_extreme_volatility', models.BooleanField(default=True, help_text='Trigger on extreme volatility')),
                ('kill_on_risk_engine_failure', models.BooleanField(default=True, help_text='Trigger if risk engine itself fails')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'risk config',
                'verbose_name_plural': 'risk configs',
                'db_table': 'risk_configs',
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('signal_approved', 'Signal Approved'), ('signal_rejected', 'Signal Rejected'), ('position_sized', 'Position Sized'), ('kill_switch_activated', 'Kill Switch Activated'), ('kill_switch_deactivated', 'Kill Switch Deactivated'), ('drawdown_warning', 'Drawdown Warning'), ('daily_loss_warning', 'Daily Loss Warning'), ('exposure_warning', 'Exposure Warning'), ('risk_limit_hit', 'Risk Limit Hit'), ('portfolio_assessed', 'Portfolio Assessed')], db_index=True, max_length=30)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('signal_id', models.UUIDField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('risk_data', models.JSONField(blank=True, default=dict)),
                ('portfolio_exposure_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('portfolio_risk_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('current_drawdown_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('daily_pnl_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('active_positions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='signals.riskconfig')),
            ],
            options={
                'verbose_name': 'risk event',
                'verbose_name_plural': 'risk events',
                'db_table': 'risk_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
