# Generated by Django 5.2.16 on 2026-08-14 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_risk_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_version', models.CharField(default='2.0', max_length=50)),
                ('feature_version', models.CharField(default='1.2', max_length=50)),
                ('model_version', models.CharField(blank=True, help_text='LLM model version if AI was used', max_length=50)),
                ('prompt_version', models.CharField(default='1.0', max_length=50)),
                ('ensemble_version', models.CharField(blank=True, max_length=50)),
                ('risk_version', models.CharField(default='1.0', max_length=50)),
                ('weights_snapshot', models.JSONField(default=dict, help_text='Exact factor weights used for this signal')),
                ('regime', models.CharField(default='unknown', help_text='Detected market regime', max_length=50)),
                ('regime_confidence', models.FloatField(default=0.0)),
                ('factor_scores', models.JSONField(default=dict, help_text='Individual factor scores')),
                ('market_snapshot', models.JSONField(default=dict, help_text='Price, indicators, candles at signal time')),
                ('news_snapshot', models.JSONField(default=dict, help_text='News articles and sentiment at signal time')),
                ('social_snapshot', models.JSONField(default=dict, help_text='Fear/greed, social sentiment at signal time')),
                ('derivatives_snapshot', models.JSONField(default=dict, help_text='Funding, OI, liquidations at signal time')),
                ('llm_context', models.JSONField(default=dict, help_text='What was sent to LLM')),
                ('llm_output', models.JSONField(default=dict, help_text='What LLM returned')),
                ('ensemble_output', models.JSONField(default=dict, help_text='Agent ensemble results')),
                ('risk_decision', models.JSONField(default=dict, help_text='Risk engine decision')),
                ('data_lineage', models.JSONField(default=dict, help_text='Complete lineage data for reproducibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineage', to='signals.signal')),
            ],
            options={
                'verbose_name': 'signal lineage',
                'verbose_name_plural': 'signal lineages',
                'db_table': 'signal_lineages',
                'ordering': ['-created_at'],
            },
        ),
    ]
