# Generated by Django 5.2.17 on 2026-08-11 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockchainEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hard_fork", "Hard Fork"),
                            ("soft_fork", "Soft Fork"),
                            ("upgrade", "Network Upgrade"),
                            ("token_unlock", "Token Unlock"),
                            ("token_burn", "Token Burn"),
                            ("hack", "Security Hack"),
                            ("exploit", "Exploit"),
                            ("bridge_hack", "Bridge Hack"),
                            ("partnership", "Partnership"),
                            ("listing", "Exchange Listing"),
                            ("delisting", "Exchange Delisting"),
                            ("other", "Other Blockchain Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("blockchain", models.CharField(max_length=50)),
                ("affected_assets", models.JSONField(default=list)),
                ("severity", models.IntegerField(default=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("neutral", "Neutral"), ("bearish", "Bearish")],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("source_url", models.URLField(blank=True)),
                ("summary", models.TextField()),
                ("event_date", models.DateTimeField(db_index=True)),
                ("amount_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "blockchain event",
                "verbose_name_plural": "blockchain events",
                "db_table": "blockchain_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="CPRAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "timeframe",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")], max_length=10
                    ),
                ),
                ("pivot", models.DecimalField(decimal_places=8, max_digits=20)),
                ("bc", models.DecimalField(decimal_places=8, max_digits=20)),
                ("tc", models.DecimalField(decimal_places=8, max_digits=20)),
                ("r1", models.DecimalField(decimal_places=8, max_digits=20)),
                ("r2", models.DecimalField(decimal_places=8, max_digits=20)),
                ("s1", models.DecimalField(decimal_places=8, max_digits=20)),
                ("s2", models.DecimalField(decimal_places=8, max_digits=20)),
                ("cpr_width", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "cpr_type",
                    models.CharField(
                        choices=[("narrow", "Narrow"), ("normal", "Normal"), ("wide", "Wide")], max_length=20
                    ),
                ),
                ("virgin_cpr", models.BooleanField(default=False)),
                ("breakout_probability", models.IntegerField(default=50)),
                ("reversal_probability", models.IntegerField(default=50)),
                ("confidence", models.IntegerField(default=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CPR analysis",
                "verbose_name_plural": "CPR analyses",
                "db_table": "cpr_analysis",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EconomicEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cpi", "Consumer Price Index"),
                            ("ppi", "Producer Price Index"),
                            ("gdp", "Gross Domestic Product"),
                            ("interest_rate", "Interest Rate Decision"),
                            ("fomc", "FOMC Meeting"),
                            ("employment", "Employment Data"),
                            ("nonfarm", "Non-Farm Payrolls"),
                            ("retail_sales", "Retail Sales"),
                            ("pmi", "Purchasing Managers Index"),
                            ("consumer_sentiment", "Consumer Sentiment"),
                            ("inflation", "Inflation Data"),
                            ("other", "Other Economic Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("country", models.CharField(default="US", max_length=10)),
                (
                    "impact_level",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("scheduled_date", models.DateTimeField(db_index=True)),
                ("actual_value", models.CharField(blank=True, max_length=100)),
                ("forecast_value", models.CharField(blank=True, max_length=100)),
                ("previous_value", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(default="%", max_length=20)),
                ("source", models.CharField(default="official", max_length=100)),
                ("is_released", models.BooleanField(default=False)),
                ("market_impact", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "economic event",
                "verbose_name_plural": "economic events",
                "db_table": "economic_events",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="GeopoliticalEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("war", "War/Conflict"),
                            ("sanctions", "Sanctions"),
                            ("election", "Election"),
                            ("government_decision", "Government Decision"),
                            ("diplomatic", "Diplomatic Event"),
                            ("trade_war", "Trade War"),
                            ("energy_crisis", "Energy Crisis"),
                            ("pandemic", "Pandemic/Health"),
                            ("natural_disaster", "Natural Disaster"),
                            ("other", "Other Geopolitical Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("region", models.CharField(max_length=50)),
                ("affected_assets", models.JSONField(default=list)),
                ("severity", models.IntegerField(default=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("neutral", "Neutral"), ("bearish", "Bearish")],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("source_url", models.URLField(blank=True)),
                ("summary", models.TextField()),
                ("event_date", models.DateTimeField(db_index=True)),
                ("expected_duration", models.CharField(default="short", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "geopolitical event",
                "verbose_name_plural": "geopolitical events",
                "db_table": "geopolitical_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="GlobalEventImpact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("economic", "Economic Event"),
                            ("regulatory", "Regulatory Event"),
                            ("geopolitical", "Geopolitical Event"),
                            ("blockchain", "Blockchain Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("impact_score", models.IntegerField(default=0)),
                ("market_reaction", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "global event impact",
                "verbose_name_plural": "global event impacts",
                "db_table": "global_event_impacts",
            },
        ),
        migrations.CreateModel(
            name="RegulatoryEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sec_decision", "SEC Decision"),
                            ("etf_approval", "ETF Approval"),
                            ("etf_rejection", "ETF Rejection"),
                            ("exchange_regulation", "Exchange Regulation"),
                            ("crypto_ban", "Crypto Ban"),
                            ("crypto_legalization", "Crypto Legalization"),
                            ("tax_regulation", "Tax Regulation"),
                            ("compliance", "Compliance Requirement"),
                            ("enforcement", "Enforcement Action"),
                            ("other", "Other Regulatory Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("jurisdiction", models.CharField(max_length=50)),
                ("affected_assets", models.JSONField(default=list)),
                ("severity", models.IntegerField(default=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("neutral", "Neutral"), ("bearish", "Bearish")],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("source_url", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("event_date", models.DateTimeField(db_index=True)),
                ("effective_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "regulatory event",
                "verbose_name_plural": "regulatory events",
                "db_table": "regulatory_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="SmartMoneyEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("bos", "Break of Structure"),
                            ("choch", "Change of Character"),
                            ("liquidity_sweep", "Liquidity Sweep"),
                            ("order_block", "Order Block"),
                            ("fvg", "Fair Value Gap"),
                            ("premium_discount", "Premium/Discount Zone"),
                            ("mitigation", "Mitigation Block"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(choices=[("bullish", "Bullish"), ("bearish", "Bearish")], max_length=10),
                ),
                ("price_zone", models.JSONField(default=dict)),
                ("confidence", models.IntegerField(default=50)),
                ("timeframe", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "smart money event",
                "verbose_name_plural": "smart money events",
                "db_table": "analytics_smart_money_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalPattern",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("head_shoulders", "Head and Shoulders"),
                            ("inverse_head_shoulders", "Inverse Head and Shoulders"),
                            ("double_top", "Double Top"),
                            ("double_bottom", "Double Bottom"),
                            ("triangle_asc", "Ascending Triangle"),
                            ("triangle_desc", "Descending Triangle"),
                            ("flag_bull", "Bull Flag"),
                            ("flag_bear", "Bear Flag"),
                            ("wedge_rising", "Rising Wedge"),
                            ("wedge_falling", "Falling Wedge"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence", models.IntegerField(default=50)),
                (
                    "direction",
                    models.CharField(choices=[("bullish", "Bullish"), ("bearish", "Bearish")], max_length=20),
                ),
                ("price_zone", models.JSONField(default=dict)),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "technical pattern",
                "verbose_name_plural": "technical patterns",
                "db_table": "analytics_technical_patterns",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "indicator_name",
                    models.CharField(
                        choices=[
                            ("ema_9", "EMA 9"),
                            ("ema_21", "EMA 21"),
                            ("ema_50", "EMA 50"),
                            ("ema_200", "EMA 200"),
                            ("sma_20", "SMA 20"),
                            ("rsi_14", "RSI 14"),
                            ("macd", "MACD"),
                            ("stochastic", "Stochastic"),
                            ("bollinger", "Bollinger Bands"),
                            ("atr", "ATR"),
                            ("adx", "ADX"),
                            ("obv", "OBV"),
                            ("mfi", "MFI"),
                            ("cci", "CCI"),
                            ("vwap", "VWAP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timeframe", models.CharField(db_index=True, max_length=10)),
                ("value", models.DecimalField(decimal_places=8, max_digits=20)),
                ("score", models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                (
                    "signal",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("neutral", "Neutral"), ("bearish", "Bearish")],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "indicator",
                "verbose_name_plural": "indicators",
                "db_table": "indicators",
                "unique_together": {("symbol", "indicator_name", "timeframe", "timestamp")},
            },
        ),
    ]
