# Generated by Django 5.2.17 on 2026-08-11 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_market", "Daily Market Report"),
                            ("weekly_ai", "Weekly AI Report"),
                            ("signal_performance", "Signal Performance"),
                            ("portfolio", "Portfolio Report"),
                            ("learning", "Learning Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.JSONField(default=dict)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "db_table": "reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
