# Generated by Django 5.2.16 on 2026-08-12 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('forecasts_created', models.IntegerField(default=0)),
                ('forecasts_verified', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0)),
                ('avg_confidence', models.FloatField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('weights_before', models.JSONField(default=dict, help_text='Model weights before this cycle')),
                ('weights_after', models.JSONField(default=dict, help_text='Model weights after learning')),
                ('adjustments_made', models.JSONField(default=list, help_text='List of weight adjustments')),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'forecast_cycles',
                'ordering': ['-cycle_time'],
            },
        ),
        migrations.CreateModel(
            name='ModelWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='BTC', max_length=10)),
                ('technical_weight', models.FloatField(default=0.35)),
                ('sentiment_weight', models.FloatField(default=0.15)),
                ('news_weight', models.FloatField(default=0.1)),
                ('ai_weight', models.FloatField(default=0.25)),
                ('macro_weight', models.FloatField(default=0.15)),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0)),
                ('avg_confidence_when_correct', models.FloatField(default=0.5)),
                ('avg_confidence_when_wrong', models.FloatField(default=0.5)),
                ('adjustment_count', models.IntegerField(default=0)),
                ('last_adjustment', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_weights',
                'unique_together': {('symbol',)},
            },
        ),
        migrations.CreateModel(
            name='PriceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('BNB', 'BNB'), ('XRP', 'XRP')], default='BTC', max_length=10)),
                ('current_price', models.FloatField(help_text='Price at time of forecast')),
                ('predicted_price', models.FloatField(help_text='Predicted price at target time')),
                ('predicted_direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('SIDEWAYS', 'Sideways')], max_length=10)),
                ('confidence', models.FloatField(help_text='Confidence score 0-1')),
                ('technical_score', models.FloatField(default=50)),
                ('regime_score', models.FloatField(default=50)),
                ('momentum_score', models.FloatField(default=50)),
                ('volatility_score', models.FloatField(default=50)),
                ('forecast_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_time', models.DateTimeField(help_text='When prediction should be checked')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('actual_direction', models.CharField(blank=True, choices=[('UP', 'Up'), ('DOWN', 'Down'), ('SIDEWAYS', 'Sideways')], max_length=10, null=True)),
                ('price_error_pct', models.FloatField(blank=True, null=True)),
                ('direction_correct', models.BooleanField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'price_forecasts',
                'ordering': ['-forecast_time'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='price_forec_symbol_66c3d0_idx'), models.Index(fields=['forecast_time'], name='price_forec_forecas_ccf251_idx'), models.Index(fields=['target_time'], name='price_forec_target__41a031_idx')],
            },
        ),
    ]
