# Generated by Django 5.2.17 on 2026-08-11 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS Feed"),
                            ("twitter", "Twitter/X"),
                            ("reddit", "Reddit"),
                            ("telegram", "Telegram"),
                            ("blog", "Official Blog"),
                            ("government", "Government"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("fetch_interval", models.IntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "news source",
                "verbose_name_plural": "news sources",
                "db_table": "news_sources",
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("language", models.CharField(default="en", max_length=10)),
                ("published_at", models.DateTimeField(db_index=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("neutral", "Neutral"), ("bearish", "Bearish")],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("impact_score", models.IntegerField(default=50)),
                ("ai_summary", models.TextField(blank=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="news.newssource"
                    ),
                ),
            ],
            options={
                "verbose_name": "news article",
                "verbose_name_plural": "news articles",
                "db_table": "news_articles",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsEntity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("crypto", "Cryptocurrency"),
                            ("company", "Company"),
                            ("person", "Person"),
                            ("event", "Event"),
                            ("regulation", "Regulation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sentiment", models.CharField(default="neutral", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entities", to="news.newsarticle"
                    ),
                ),
            ],
            options={
                "verbose_name": "news entity",
                "verbose_name_plural": "news entities",
                "db_table": "news_entities",
                "unique_together": {("article", "name")},
            },
        ),
    ]
