# Generated by Django 5.2.16 on 2026-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssource',
            options={'ordering': ['-reliability_score', 'name'], 'verbose_name': 'news source', 'verbose_name_plural': 'news sources'},
        ),
        migrations.AddField(
            model_name='newssource',
            name='category',
            field=models.CharField(blank=True, default='crypto_news', max_length=50),
        ),
        migrations.AddField(
            model_name='newssource',
            name='icon',
            field=models.CharField(blank=True, default='📰', max_length=10),
        ),
        migrations.AddField(
            model_name='newssource',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newssource',
            name='reliability_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='newssource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS Feed'), ('twitter', 'Twitter/X'), ('reddit', 'Reddit'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('blog', 'Official Blog'), ('government', 'Government')], max_length=20),
        ),
    ]
