# Generated by Django 5.2.16 on 2026-08-11 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('portfolio_type', models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures'), ('combined', 'Combined')], default='spot', max_length=30)),
                ('total_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_invested_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pnl_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pnl_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('beta', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('base_currency', models.CharField(default='USDT', max_length=10)),
                ('auto_rebalance', models.BooleanField(default=False)),
                ('rebalance_threshold_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
                'db_table': 'portfolios',
                'ordering': ['-total_value_usd'],
            },
        ),
        migrations.CreateModel(
            name='RebalanceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trades_executed', models.JSONField(default=list, help_text='List of trades executed')),
                ('total_trades', models.IntegerField(default=0)),
                ('total_fees_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('portfolio_value_before', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('portfolio_value_after', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ai_reasoning', models.TextField(blank=True, help_text='AI explanation for rebalance decisions')),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('threshold', 'Threshold Breached'), ('manual', 'Manual'), ('ai', 'AI Recommendation')], default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalance_history', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'rebalance history',
                'verbose_name_plural': 'rebalance histories',
                'db_table': 'rebalance_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_year', models.IntegerField()),
                ('tax_country', models.CharField(default='US', max_length=3)),
                ('total_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('short_term_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('short_term_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('long_term_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('long_term_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('transactions', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'tax report',
                'verbose_name_plural': 'tax reports',
                'db_table': 'tax_reports',
                'ordering': ['-tax_year'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('target_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('current_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('needs_rebalance', models.BooleanField(default=False)),
                ('rebalance_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'portfolio allocation',
                'verbose_name_plural': 'portfolio allocations',
                'db_table': 'portfolio_allocations',
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='TaxLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('acquisition_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('cost_basis_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('cost_basis_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('disposition_date', models.DateField(blank=True, null=True)),
                ('proceeds_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('gain_loss_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('gain_loss_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('holding_period_days', models.IntegerField(default=0)),
                ('is_long_term', models.BooleanField(default=False, help_text='Held for more than 1 year')),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_closed', 'Partially Closed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('remaining_quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source', models.CharField(choices=[('purchase', 'Purchase'), ('trade', 'Trade'), ('transfer', 'Transfer'), ('mining', 'Mining'), ('staking', 'Staking'), ('airdrop', 'Airdrop')], default='purchase', max_length=30)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lots', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'tax lot',
                'verbose_name_plural': 'tax lots',
                'db_table': 'tax_lots',
                'ordering': ['acquisition_date'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='tax_lots_symbol_da9c6e_idx'), models.Index(fields=['acquisition_date'], name='tax_lots_acquisi_b15485_idx')],
            },
        ),
    ]
