# Generated by Django 5.2.17 on 2026-08-11 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWatchlist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("display_name", models.CharField(blank=True, max_length=50)),
                ("coin_id", models.CharField(blank=True, max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("is_favorite", models.BooleanField(default=False)),
                ("price_alert_above", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("price_alert_below", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "watchlist item",
                "verbose_name_plural": "watchlist items",
                "db_table": "user_watchlist",
                "ordering": ["order", "-created_at"],
                "unique_together": {("user", "symbol")},
            },
        ),
    ]
