# Generated by Django 5.2.16 on 2026-08-12 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('market_analysis', 'Market Analysis'), ('signal_review', 'Signal Review'), ('news_digest', 'News Digest'), ('sentiment_report', 'Sentiment Report'), ('technical_review', 'Technical Review'), ('macro_outlook', 'Macro Outlook'), ('daily_summary', 'Daily Summary'), ('weekly_summary', 'Weekly Summary'), ('lessons_learned', 'Lessons Learned')], default='market_analysis', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='Brief AI summary of the entry')),
                ('symbols_analyzed', models.JSONField(default=list, help_text='List of symbols discussed')),
                ('market_sentiment', models.CharField(choices=[('very_bullish', 'Very Bullish'), ('bullish', 'Bullish'), ('neutral', 'Neutral'), ('bearish', 'Bearish'), ('very_bearish', 'Very Bearish')], default='neutral', max_length=20)),
                ('composite_score', models.FloatField(default=50, help_text='Overall market score 0-100')),
                ('data_sources', models.JSONField(default=list, help_text='Sources: news, technical, sentiment, etc.')),
                ('news_count', models.IntegerField(default=0, help_text='Number of news articles analyzed')),
                ('indicators_used', models.JSONField(default=list, help_text='Technical indicators referenced')),
                ('ai_model', models.CharField(default='gemma4:latest', max_length=50)),
                ('ai_confidence', models.FloatField(default=0.5, help_text='AI confidence in its analysis 0-1')),
                ('ai_reasoning', models.TextField(blank=True, help_text='Step-by-step AI reasoning')),
                ('key_findings', models.JSONField(default=list, help_text='List of key findings')),
                ('risks_identified', models.JSONField(default=list, help_text='List of risks')),
                ('opportunities', models.JSONField(default=list, help_text='List of opportunities')),
                ('tags', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'journal entry',
                'verbose_name_plural': 'journal entries',
                'db_table': 'journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern Detected'), ('correlation', 'Correlation Found'), ('anomaly', 'Anomaly Detected'), ('trend', 'Trend Identified'), ('risk_alert', 'Risk Alert'), ('opportunity', 'Opportunity Found')], max_length=20)),
                ('description', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Structured insight data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='journal.journalentry')),
            ],
            options={
                'verbose_name': 'journal insight',
                'verbose_name_plural': 'journal insights',
                'db_table': 'journal_insights',
            },
        ),
        migrations.CreateModel(
            name='MarketContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('btc_price', models.FloatField(default=0)),
                ('eth_price', models.FloatField(default=0)),
                ('btc_dominance', models.FloatField(default=0)),
                ('fear_greed_index', models.IntegerField(default=50)),
                ('fear_greed_label', models.CharField(default='Neutral', max_length=20)),
                ('total_market_cap', models.FloatField(default=0)),
                ('total_volume_24h', models.FloatField(default=0)),
                ('btc_trend', models.CharField(default='neutral', max_length=20)),
                ('btc_rsi', models.FloatField(default=50)),
                ('btc_macd_signal', models.CharField(default='neutral', max_length=20)),
                ('news_sentiment_score', models.FloatField(default=50)),
                ('breaking_news_count', models.IntegerField(default=0)),
                ('top_news_headlines', models.JSONField(default=list)),
                ('social_sentiment_score', models.FloatField(default=50)),
                ('funding_rate_avg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_context', to='journal.journalentry')),
            ],
            options={
                'verbose_name': 'market context',
                'verbose_name_plural': 'market contexts',
                'db_table': 'journal_market_contexts',
            },
        ),
    ]
