# Generated by Django 5.2.16 on 2026-08-12 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sources_used',
            field=models.JSONField(default=list, help_text='Specific news sources used in this entry'),
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('api', 'API'), ('web', 'Website'), ('twitter', 'Twitter/X'), ('reddit', 'Reddit'), ('telegram', 'Telegram')], default='rss', max_length=20)),
                ('category', models.CharField(choices=[('crypto_news', 'Crypto News'), ('market_data', 'Market Data'), ('defi', 'DeFi'), ('nft', 'NFT'), ('regulation', 'Regulation'), ('macro', 'Macro Economics'), ('on_chain', 'On-Chain Data'), ('social', 'Social Media')], default='crypto_news', max_length=20)),
                ('icon', models.CharField(default='📰', max_length=10)),
                ('reliability_score', models.IntegerField(default=50, help_text='Source reliability 0-100')),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary sources always included')),
                ('tags', models.JSONField(default=list, help_text='Topics covered by this source')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('fetch_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'news source',
                'verbose_name_plural': 'news sources',
                'db_table': 'journal_news_sources',
                'ordering': ['-reliability_score', 'name'],
            },
        ),
    ]
