# Generated by Django 5.2.16 on 2026-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_sources_used_newssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='language',
            field=models.CharField(default='en', help_text='Language code: en for English, fa for Persian', max_length=5),
        ),
    ]
