"""Email service for sending performance reports and alerts."""
import logging
from typing import Dict, List, Optional
from datetime import datetime, timedelta
from django.core.mail import send_mail
from django.conf import settings

logger = logging.getLogger(__name__)


class EmailService:
    """Send email notifications for trading signals and performance."""

    @staticmethod
    def send_daily_report(user_email: str, report_data: Dict) -> bool:
        """Send daily performance report via email."""
        try:
            subject = f"AI-Trading Daily Report - {datetime.now().strftime('%Y-%m-%d')}"
            
            # Build email body
            body = f"""
AI-Trading Daily Performance Report
{'=' * 50}

Period: {report_data.get('period', 'Last 24 hours')}

SIGNALS SUMMARY
---------------
Total Signals: {report_data.get('total_signals', 0)}
Win Rate: {report_data.get('win_rate', 0):.1f}%
Average Confidence: {report_data.get('avg_confidence', 0):.1f}%

TOP PERFORMERS
--------------
"""
            for signal in report_data.get('top_performers', [])[:5]:
                body += f"  {signal.get('symbol', 'N/A')}: {signal.get('return_pct', 0):+.2f}%\n"
            
            body += f"""
PORTFOLIO
---------
Current Equity: ${report_data.get('equity', 0):,.2f}
Total Return: {report_data.get('total_return', 0):+.2f}%
Max Drawdown: {report_data.get('max_drawdown', 0):.2f}%

AI MODEL PERFORMANCE
--------------------
"""
            for model in report_data.get('model_performance', []):
                body += f"  {model.get('name', 'N/A')}: {model.get('accuracy', 0):.1f}% accuracy\n"
            
            body += f"""
---
Generated by AI-Trading Platform
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
            
            send_mail(
                subject=subject,
                message=body,
                from_email=settings.DEFAULT_FROM_EMAIL if hasattr(settings, 'DEFAULT_FROM_EMAIL') else 'noreply@ai-trading.com',
                recipient_list=[user_email],
                fail_silently=False,
            )
            
            logger.info(f"Daily report sent to {user_email}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send daily report: {e}")
            return False

    @staticmethod
    def send_signal_alert(user_email: str, signal_data: Dict) -> bool:
        """Send alert when high-confidence signal is generated."""
        try:
            symbol = signal_data.get('symbol', 'UNKNOWN')
            direction = signal_data.get('direction', 'hold').upper()
            confidence = signal_data.get('confidence', 0)
            
            subject = f"🚨 Signal Alert: {symbol} {direction} ({confidence}%)"
            
            body = f"""
SIGNAL ALERT
{'=' * 50}

Symbol: {signal_data.get('symbol', 'N/A')}
Direction: {direction}
Confidence: {confidence}%
Price: ${signal_data.get('price', 0):,.2f}
Timeframe: {signal_data.get('timeframe', 'N/A')}

COMPOSITE SCORE: {signal_data.get('composite_score', 0):.1f}/100

FACTOR BREAKDOWN
----------------
Technical: {signal_data.get('technical_score', 0):.1f}
Sentiment: {signal_data.get('sentiment_score', 0):.1f}
News: {signal_data.get('news_score', 0):.1f}
Macro: {signal_data.get('macro_score', 0):.1f}

AI VERDICT: {signal_data.get('ai_verdict', 'N/A')}
AI CONFIDENCE: {signal_data.get('ai_confidence', 0)}%

---
Generated by AI-Trading Platform
"""
            
            send_mail(
                subject=subject,
                message=body,
                from_email=settings.DEFAULT_FROM_EMAIL if hasattr(settings, 'DEFAULT_FROM_EMAIL') else 'noreply@ai-trading.com',
                recipient_list=[user_email],
                fail_silently=False,
            )
            
            logger.info(f"Signal alert sent to {user_email}: {symbol} {direction}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send signal alert: {e}")
            return False

    @staticmethod
    def send_weekly_summary(user_email: str, summary_data: Dict) -> bool:
        """Send weekly performance summary."""
        try:
            subject = f"AI-Trading Weekly Summary - {datetime.now().strftime('%Y-%m-%d')}"
            
            body = f"""
AI-Trading Weekly Performance Summary
{'=' * 50}

Week: {summary_data.get('week_start', 'N/A')} to {summary_data.get('week_end', 'N/A')}

PERFORMANCE METRICS
-------------------
Total Signals: {summary_data.get('total_signals', 0)}
Winning Signals: {summary_data.get('winning_signals', 0)}
Losing Signals: {summary_data.get('losing_signals', 0)}
Win Rate: {summary_data.get('win_rate', 0):.1f}%

PROFIT/LOSS
-----------
Total PnL: ${summary_data.get('total_pnl', 0):+,.2f}
Best Trade: ${summary_data.get('best_trade', 0):+,.2f}
Worst Trade: ${summary_data.get('worst_trade', 0):+,.2f}
Average Trade: ${summary_data.get('avg_trade', 0):+,.2f}

AI PERFORMANCE
--------------
"""
            for model in summary_data.get('model_performance', []):
                body += f"  {model.get('name', 'N/A')}: {model.get('accuracy', 0):.1f}% accuracy ({model.get('predictions', 0)} predictions)\n"
            
            body += f"""
CALIBRATION STATUS
------------------
Brier Score: {summary_data.get('brier_score', 0):.4f}
Calibration Quality: {summary_data.get('calibration_quality', 'N/A')}

---
Generated by AI-Trading Platform
"""
            
            send_mail(
                subject=subject,
                message=body,
                from_email=settings.DEFAULT_FROM_EMAIL if hasattr(settings, 'DEFAULT_FROM_EMAIL') else 'noreply@ai-trading.com',
                recipient_list=[user_email],
                fail_silently=False,
            )
            
            logger.info(f"Weekly summary sent to {user_email}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send weekly summary: {e}")
            return False
