# Generated by Django 5.2.16 on 2026-08-11 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_spread_percent', models.DecimalField(decimal_places=4, default=0.5, max_digits=10)),
                ('max_risk_score', models.IntegerField(default=70)),
                ('enabled_exchanges', models.JSONField(default=list, help_text='List of exchanges to monitor')),
                ('monitored_symbols', models.JSONField(default=list, help_text='List of symbols to monitor')),
                ('check_interval_seconds', models.IntegerField(default=30)),
                ('max_position_size_usd', models.DecimalField(decimal_places=2, default=10000, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'arbitrage config',
                'verbose_name_plural': 'arbitrage configs',
                'db_table': 'arbitrage_configs',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('buy_exchange', models.CharField(max_length=50)),
                ('sell_exchange', models.CharField(max_length=50)),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estimated_profit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('volume_available', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('fees_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('net_profit_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('risk_score', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('executed', 'Executed'), ('missed', 'Missed')], default='active', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'arbitrage opportunity',
                'verbose_name_plural': 'arbitrage opportunities',
                'db_table': 'arbitrage_opportunities',
                'ordering': ['-spread_percent'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='arbitrage_o_symbol_483bc1_idx'), models.Index(fields=['-spread_percent'], name='arbitrage_o_spread__a579e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArbitrageExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('buying', 'Buying'), ('selling', 'Selling'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('buy_order_id', models.CharField(blank=True, max_length=100)),
                ('sell_order_id', models.CharField(blank=True, max_length=100)),
                ('actual_buy_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('actual_sell_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('actual_profit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='arbitrage.arbitrageopportunity')),
            ],
            options={
                'verbose_name': 'arbitrage execution',
                'verbose_name_plural': 'arbitrage executions',
                'db_table': 'arbitrage_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
