# Generated by Django 5.2.17 on 2026-08-11 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegimeAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("composite_score", models.FloatField(blank=True, null=True)),
                ("zone", models.CharField(max_length=20)),
                ("guidance", models.TextField(blank=True)),
                ("components", models.JSONField(default=dict)),
                ("exposure_posture", models.JSONField(default=dict)),
                ("universe_size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "regime_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignalReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("signal_id", models.CharField(blank=True, max_length=100)),
                ("symbol", models.CharField(max_length=20)),
                ("direction", models.CharField(max_length=10)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("exit_price", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("pnl_pct", models.FloatField(blank=True, null=True)),
                ("lesson_learned", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "signal_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillUsageLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("skill_name", models.CharField(max_length=100)),
                ("input_params", models.JSONField(default=dict)),
                ("output_summary", models.JSONField(default=dict)),
                ("execution_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "skill_usage_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
