# Generated by Django 5.2.16 on 2026-08-11 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0002_seed_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('total_signals', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_return', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('allow_copy_trading', models.BooleanField(default=False)),
                ('copy_trading_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trader',
                'verbose_name_plural': 'traders',
                'db_table': 'social_traders',
                'ordering': ['-win_rate'],
            },
        ),
        migrations.CreateModel(
            name='CopyTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pnl_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed')], default='open', max_length=20)),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_trades', to=settings.AUTH_USER_MODEL)),
                ('original_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.signal')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_trades', to='social.trader')),
            ],
            options={
                'verbose_name': 'copy trade',
                'verbose_name_plural': 'copy trades',
                'db_table': 'social_copy_trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraderSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentary', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_signals', to='signals.signal')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='social.trader')),
            ],
            options={
                'verbose_name': 'trader signal',
                'verbose_name_plural': 'trader signals',
                'db_table': 'social_trader_signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trader_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.tradersignal')),
            ],
            options={
                'verbose_name': 'social comment',
                'verbose_name_plural': 'social comments',
                'db_table': 'social_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copy_trading', models.BooleanField(default=False)),
                ('copy_position_size_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('max_copy_amount_usd', models.DecimalField(decimal_places=2, default=1000, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='social.trader')),
            ],
            options={
                'verbose_name': 'follow relationship',
                'verbose_name_plural': 'follow relationships',
                'db_table': 'social_follows',
                'unique_together': {('follower', 'trader')},
            },
        ),
    ]
