# Generated by Django 5.2.17 on 2026-08-11 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DerivativesData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("funding_rate", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("open_interest", models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ("long_short_ratio", models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ("liquidations_24h", models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "derivatives data",
                "verbose_name_plural": "derivatives data",
                "db_table": "derivatives_data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "api_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("maintenance", "Maintenance")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "exchange",
                "verbose_name_plural": "exchanges",
                "db_table": "exchanges",
            },
        ),
        migrations.CreateModel(
            name="OrderBook",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("bid_volume", models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ("ask_volume", models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ("spread", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("bid_depth", models.JSONField(default=dict)),
                ("ask_depth", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "order book",
                "verbose_name_plural": "order books",
                "db_table": "order_books",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WhaleAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=30)),
                ("usd_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("from_address", models.CharField(max_length=100)),
                ("to_address", models.CharField(max_length=100)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("exchange_inflow", "Exchange Inflow"),
                            ("exchange_outflow", "Exchange Outflow"),
                            ("whale_transfer", "Whale Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tx_hash", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "whale alert",
                "verbose_name_plural": "whale alerts",
                "db_table": "whale_alerts",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                            ("15m", "15 Minutes"),
                            ("30m", "30 Minutes"),
                            ("1h", "1 Hour"),
                            ("4h", "4 Hours"),
                            ("12h", "12 Hours"),
                            ("1d", "1 Day"),
                            ("1w", "1 Week"),
                            ("1M", "1 Month"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=30)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "candle",
                "verbose_name_plural": "candles",
                "db_table": "candles",
                "ordering": ["-timestamp"],
                "unique_together": {("symbol", "timeframe", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="TradingPair",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("base_asset", models.CharField(max_length=20)),
                ("quote_asset", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("min_order_size", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("tick_size", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="trading_pairs", to="market.exchange"
                    ),
                ),
            ],
            options={
                "verbose_name": "trading pair",
                "verbose_name_plural": "trading pairs",
                "db_table": "trading_pairs",
                "unique_together": {("exchange", "symbol")},
            },
        ),
    ]
