# Generated by Django 5.2.16 on 2026-08-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivativesdata',
            name='annualized_basis',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Annualized basis (%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='basis',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Futures premium over spot (%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='funding_rate_hourly',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Annualized funding rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='liquidation_longs_24h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='liquidation_shorts_24h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='long_account_ratio',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Ratio of long accounts', max_digits=5),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='open_interest_change_24h',
            field=models.DecimalField(decimal_places=4, default=0, help_text='OI change in % over 24h', max_digits=10),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='open_interest_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='options_iv',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Implied volatility', max_digits=10),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='put_call_ratio',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Put/Call volume ratio', max_digits=10),
        ),
        migrations.AddField(
            model_name='derivativesdata',
            name='short_account_ratio',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Ratio of short accounts', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='derivativesdata',
            index=models.Index(fields=['symbol', 'timestamp'], name='derivatives_symbol_8aac11_idx'),
        ),
    ]
